# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'new repository'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create repository
        run: |
          repo_name="my_new_repo"
          username="your_username"
          token="${{ secrets.GITTOKEN }}"
          url="https://api.github.com/user/${{ github.event.inputs.repo_name }}"
          payload="{\"name\": \"${{ github.event.inputs.repo_name }}\", \"auto_init\": true, \"private\": false}"
          response=$(curl -s -H "Authorization: token $token" -H "Accept: application/vnd.github.v3+json" -d "$payload" $url)
          if [[ $(echo "$response" | grep -c "\"html_url\":") -eq 1 ]]; then
            echo "Repository '$repo_name' created successfully!"
          else
            echo "Failed to create repository. Error message:"
            echo "$response"
            exit 1
          fi
          
          
      
