# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'new repository'
        required: true

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "ajoutane@ttuhsc.edu"
          git config --global user.name "aristidejou"

      - name: Create repository
        run: |
          curl -H "Authorization: token ${{ secrets.GITTOKEN }}" -d '{"name":"${{ github.event.inputs.repo_name }}"}' https://api.github.com/user/repos

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: aristidejou/${{ github.event.inputs.repo_name }}
          ref: master

      - name: Create README file
        run: |
          cd your-repository-name
          touch README.md
          git add README.md
          git commit -m "Initial commit"
          git push origin master
